language: python
python:
 - "3.5"

install:
 - pip install requests
env:
  - API_KEY=supersecretkey

# command to run tests
script:
 - python -m unittest TestTriangle
 - python HW 05a_mocking\main.py
